name: cti-python-stix2-extensions tests were skipped
on:
  push:
    paths:
      - '!**.py'
      - '!**/tox.ini'
      - '!**/pyproject.toml'
      - '!**/tox.ini'
      - '!**/workflows/**.yml'
  pull_request:
    paths:
      - '!**.py'
      - '!**/tox.ini'
      - '!**/pyproject.toml'
      - '!**/workflows/**.yml'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "No code changes found to test"

